### ISSUE TITLE
Access to Unit type

### ISSUE THREAD

**Issue by jpearll** [bcicen/go-units#12]
Hi

Is there a way we can get access to the Unit when declaring a NewValue ?

For example, if 
`
total := units.NewValue(900, units.Second)
`
From 'total', I would like to have access to the unit type (units.Second)

Thanks

**Comment by bcicen** [comment]
previously, no; though, I don't believe there's a good reason for this so I've added `value.Unit()` [here](https://godocs.io/github.com/bcicen/go-units#Value.Unit)

thanks again for the feedback
