### ISSUE TITLE
adding units

### ISSUE THREAD

**Issue by redurgam** [bcicen/go-units#19]
firstly want to say thanks for the author(s) work on this.

i went to the volume_units.go file and had a crack at adding in teaspoon, tablespoon, cup
https://pst.klgrth.io/paste/uycru

is this basically all there is to it? if so i'd like to submit more units as i come across them

**Comment by bcicen** [comment]
Thanks @redurgam! Glad you're finding it useful.
 
That is indeed all there is to adding new units; feel free to submit a pull request anytime.
